### ISSUE TITLE
Cannot get the /register link to work

### ISSUE THREAD

**Issue by dirkhh** [trac-hacks/trac-recaptcharegister#2]
Trac 1.0
TracAccountManager 0.4.4

* recaptcharegister installed from git master
* trac log shows that it's loading the recaptcharegister module
* in trac.ini, section `[components]` I have

```
acct_mgr.web_ui.registrationmodule = disabled
recaptcharegister.* = enabled
[recaptcha] has public and private key set
```

When I go to my Trac website there is no Register link, when I manually add `/register` to the URL I get an error. So somewhere it seems the plugin isn't registered correctly, but I can't figure out how and where...

**Comment by akos-ladanyi** [comment]
Same problem here.
* Trac 1.0.1
* TracAccountManager 0.4.3
* TracRecaptchaRegister 0.3.2

**Comment by samm-git** [comment]
You dont need to disable registrationmodule, because this plugin works as a filter and using native /register handler.
